name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - run: false
  
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
    - run: true
 
  test3:
    runs-on: ubuntu-latest
    needs: test1
    if: always()
    steps:
    - run: echo '${{ needs.test1 }}'
