name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test1:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: false
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: true
      if: ${{ matrix.os == 'macos-latest' }}
      
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
    - run: true
 
  test3:
    runs-on: ubuntu-latest
    needs: test1
    if: always()
    steps:
    - run: echo '${{ needs.test1.result }}'
